### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by pictron** [hissy/addon_ssl_redirect_conf#1]
dashbord,multilanguage page

ssl_redirect_conf/src/Concrete/Http/PathRequestMatcher.php

foreach ($paths as $path) {
if ($request->matches($path)) {
return true;
}
}

**Comment by hissy** [comment]
取り急ぎ、パスの設定が配列かどうかチェックし、配列でない場合は処理をスキップするように修正しました。パスの設定はどんな設定にしたかわかりますか？

**Comment by pictron** [comment]
いやインストールして設定する前になったんだけどね

**Comment by hissy** [comment]
あ、なるほど、バグですね。治ってると思います

**Comment by pictron** [comment]
インストールまではいきました、管理画面で設定しようとすると
implode(): Invalid arguments passed

**Comment by katzueno** [comment]
あ、自分もこのエラー出ました

`implode(): Invalid arguments passed`

![environment](https://cloud.githubusercontent.com/assets/485751/11949356/77fe83fa-a8c1-11e5-8b25-31dc86be815e.png)

**Comment by hissy** [comment]
直します

**Comment by hissy** [comment]
@各位

スンマセン直しました。

**Comment by katzueno** [comment]
治った！！！
使えた！！
