### ISSUE TITLE
再編集

### ISSUE THREAD

**Issue by pictron** [hissy/addon_ssl_redirect_conf#4]
一度設定したものを再編集できません。
ただ、メールした。
 This request has been blocked; the content must be served over HTTPS.
のせいだと思いますが、いったん設定していない状態にするには、ＤＢでどこを消せばいいのでしょう？

**Comment by hissy** [comment]
設定ファイルに書き込まれてます。詳細はKatzさんがREADMEに書いてくれました

**Comment by pictron** [comment]
設定ファイルを削除したら戻りました。これはこのアドオンの問題じゃやないかもしれませんがhttps化したときのデフォルトで読み込んでるjQuery-uiなどの
This request has been blocked; the content must be served over HTTPS.
が出て動かない問題は、どう対処すればいいんでしょう？フォーラムネタでしょうか？

**Comment by hissy** [comment]
カノニカルURLを設定してますか？

**Comment by pictron** [comment]
URLs and Redirectionのとこの事ですか？
そこはCanonical URLにhttp://〜
SSL URLにhttps://〜
を入れてます。

**Comment by hissy** [comment]
カノニカルURLを空にすると直ります。次のバージョンで修正されると思いますが、今GitHub上でやりとりしてます

**Comment by pictron** [comment]
URLs and Redirectionのとこを直すとページ名通りのページはリダイレクトいけました。
ですが、「問い合わせ」ページをページの場所設定でカノニカルURLで「contact-us」にしているページがリダイレクトしません。

**Comment by hissy** [comment]
ルールはどうなってますか？

**Comment by pictron** [comment]
変えたいところはページ名が「問い合わせ」で
/jp/contact-us
で

設定は
/login
/login/*
/dashboard
/dashboard/*
/jp/contact-us
/en/contact-us

/en/contact-usはリダイレクトしてます。
これはページ名もcontact-us
そういう事であってる？

**Comment by hissy** [comment]
このアドオンはページの設定は見ていません。ブラウザに入力されたURLとだけ比較しています。

**Comment by pictron** [comment]
うーん、なんでだろう俺の設定かな〜
英語のペアリングの/en/contact-usから言語切り換えで/jp/contact-usに行くとちゃんとSSLになってるのに、日本語ナビメニューから行くとSSLにならない。autonaviでページに行ってるだけなんだけど．．．
