### ISSUE TITLE
Using concrete5 CLI command to build ZIP?

### ISSUE THREAD

**Issue by mlocati** [hissy/addon_ssl_redirect_conf#5]
Hi Takuro,

I was looking at this package and I saw that you use Gulp to build the package ZIP archive.

I just wondered if you knew that you could simply use this command:
`concrete/bin/concrete5 c5:package-pack -z <PATH_OF_ZIP_FILE> ssl_redirect_conf`
to save the .zip file as `<PATH_OF_ZIP_FILE>`
-or-
`concrete/bin/concrete5 c5:package-pack -z- ssl_redirect_conf`
To save the zip file in the packages folder.

More info here: http://documentation.concrete5.org/developers/appendix/cli-commands#c5-package-pack

**Comment by hissy** [comment]
I know your pull request have been merged. thanks.

**Comment by mlocati** [comment]
:+1:
